language: node_js
node_js:
- 10.12.0
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
after_script:
- tar -zcvf dist.tar.gz ./dist/
deploy:
  provider: releases
  api_key:
    secure: 65c3570e726186246c9ecc92397a604adcdc5b7e
  file: dist.tar.gz
  on:
    tags: true
